#!/bin/sh

set -e

case "$1" in
    configure|reconfigure)
        virsh nwfilter-define /usr/share/libvirt-fsinf/nwfilter/clean-traffic-fsinf.xml
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#
