#!/bin/sh

set -e

case "$1" in
    configure|reconfigure)
        for filename in /usr/share/libvirt-fsinf/nwfilter/*.xml; do
            virsh nwfilter-define $filename
        done
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#
